# Generated by Django 3.2 on 2022-06-05 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='program',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='student',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='changed_by',
        ),
    ]
