# Generated by Django 3.2 on 2022-06-08 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_auto_20220607_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='open_programs',
        ),
        migrations.AddField(
            model_name='student',
            name='open_program',
            field=models.ManyToManyField(related_name='students', to='education.Program'),
        ),
    ]
