# Generated by Django 3.2 on 2022-06-08 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_auto_20220608_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='wish_program',
            field=models.ManyToManyField(to='education.Program'),
        ),
    ]
