# Generated by Django 3.2 on 2022-06-08 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0008_auto_20220608_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='wish_program',
            field=models.ManyToManyField(blank=True, null=True, to='education.Program'),
        ),
    ]
