# Generated by Django 3.2 on 2022-06-10 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0009_alter_student_wish_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='education.program'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='education.program'),
        ),
    ]
