# Generated by Django 3.2 on 2022-06-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0011_answer_category_question_quizzes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizzes',
            options={'ordering': ['id'], 'verbose_name': 'Program', 'verbose_name_plural': 'Programs'},
        ),
        migrations.RemoveField(
            model_name='quizzes',
            name='category',
        ),
        migrations.AlterField(
            model_name='quizzes',
            name='title',
            field=models.CharField(default='New Program', max_length=255, verbose_name='Program Title'),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
