# Generated by Django 3.2 on 2022-06-12 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0015_alter_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='studying',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studying', to='education.program'),
        ),
    ]
