# Generated by Django 3.2 on 2022-06-12 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0017_alter_studying_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studying',
            name='program',
        ),
        migrations.AlterField(
            model_name='studying',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studying', to='education.lesson'),
        ),
    ]
