# Generated by Django 3.2.1 on 2022-07-08 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photoschool', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='open_program',
            new_name='open_programs',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='wish_program',
            new_name='wish_programs',
        ),
    ]
